package com.chiyumechunga.chaincode;

import com.owlike.genson.annotation.JsonProperty;
import org.hyperledger.fabric.contract.annotation.DataType;
import org.hyperledger.fabric.contract.annotation.Property;
import java.util.Objects;

/**
 * Represents a Pharmaceutical Batch on the Ledger.
 * ALIGNMENT: Uses @JsonProperty to match Backend DTO snake_case fields.
 *
 * NOTE: qr_hash is initially empty and populated by backend after blockchain confirmation.
 */
@DataType()
public class DrugTruth {

    @Property()
    @JsonProperty("batch_number")
    private String batchNumber;

    @Property()
    @JsonProperty("product_name")
    private String productName;

    @Property()
    @JsonProperty("manufacturer_id")
    private String manufacturerId;

    @Property()
    @JsonProperty("expiry_date")
    private String expiryDate;

    @Property()
    @JsonProperty("qr_hash")
    private String qrHash; // Generated by backend post-creation

    @Property()
    @JsonProperty("current_owner")
    private String currentOwner; // Fabric MSP ID

    @Property()
    @JsonProperty("current_owner_uuid")
    private String currentOwnerUuid; // Postgres UUID

    @Property()
    @JsonProperty("status")
    private String status;

    // --- Constructors ---

    public DrugTruth() {
        this.batchNumber = "";
        this.productName = "";
        this.manufacturerId = "";
        this.expiryDate = "";
        this.qrHash = "";
        this.currentOwner = "";
        this.currentOwnerUuid = "";
        this.status = "";
    }

    public DrugTruth(@JsonProperty("batch_number") String batchNumber,
                     @JsonProperty("product_name") String productName,
                     @JsonProperty("manufacturer_id") String manufacturerId,
                     @JsonProperty("expiry_date") String expiryDate,
                     @JsonProperty("qr_hash") String qrHash,
                     @JsonProperty("current_owner") String currentOwner,
                     @JsonProperty("current_owner_uuid") String currentOwnerUuid,
                     @JsonProperty("status") String status) {
        this.batchNumber = batchNumber;
        this.productName = productName;
        this.manufacturerId = manufacturerId;
        this.expiryDate = expiryDate;
        this.qrHash = qrHash;
        this.currentOwner = currentOwner;
        this.currentOwnerUuid = currentOwnerUuid;
        this.status = status;
    }

    // --- Getters & Setters ---

    public String getBatchNumber() { return batchNumber; }
    public String getProductName() { return productName; }
    public String getManufacturerId() { return manufacturerId; }
    public String getExpiryDate() { return expiryDate; }
    public String getQrHash() { return qrHash; }
    public String getCurrentOwner() { return currentOwner; }
    public String getCurrentOwnerUuid() { return currentOwnerUuid; }
    public String getStatus() { return status; }

    public void setCurrentOwner(String currentOwner) { this.currentOwner = currentOwner; }
    public void setCurrentOwnerUuid(String currentOwnerUuid) { this.currentOwnerUuid = currentOwnerUuid; }
    public void setStatus(String status) { this.status = status; }
    public void setQrHash(String qrHash) { this.qrHash = qrHash; }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        DrugTruth drugTruth = (DrugTruth) o;
        return Objects.equals(batchNumber, drugTruth.batchNumber) &&
                Objects.equals(productName, drugTruth.productName) &&
                Objects.equals(manufacturerId, drugTruth.manufacturerId) &&
                Objects.equals(expiryDate, drugTruth.expiryDate) &&
                Objects.equals(qrHash, drugTruth.qrHash) &&
                Objects.equals(currentOwner, drugTruth.currentOwner) &&
                Objects.equals(currentOwnerUuid, drugTruth.currentOwnerUuid) &&
                Objects.equals(status, drugTruth.status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(batchNumber, productName, manufacturerId, expiryDate, qrHash, currentOwner, currentOwnerUuid, status);
    }
}