package com.chiyumechunga.backend.controller;

import com.chiyumechunga.backend.dto.ParticipantRegistrationDto;
import com.chiyumechunga.backend.dto.ParticipantResponseDto; // Import the new DTO
import com.chiyumechunga.backend.model.SupplyChainParticipant;
import com.chiyumechunga.backend.service.ParticipantService;
import jakarta.validation.Valid;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.util.HtmlUtils;

@Slf4j
@RestController
@RequestMapping("/api/v1/participants")
public class ParticipantController {

    private final ParticipantService participantService;

    public ParticipantController(ParticipantService participantService) {
        this.participantService = participantService;
    }

    @PostMapping
    public ResponseEntity<ParticipantResponseDto> register(@Valid @RequestBody ParticipantRegistrationDto request) {
        log.info("Request to onboard participant.");

        // 1. STRICT SANITIZATION (Defense in Depth)
        // Even though we don't return these values, we sanitize them before DB insertion.
        ParticipantRegistrationDto safeRequest = new ParticipantRegistrationDto(
                sanitizeStrict(request.participantCode()),
                HtmlUtils.htmlEscape(request.participantName()),
                request.participantType(),
                HtmlUtils.htmlEscape(request.country()),
                sanitizeStrict(request.blockchainEnrollmentId())
        );

        // 2. PROCESS
        SupplyChainParticipant newParticipant = participantService.registerParticipant(safeRequest);

        // 3. BREAK TAINT CHAIN (The Fix)
        // The security tool flags "newParticipant" because it contains data from "request".
        // Instead, we create a NEW response object using ONLY the system-generated ID.
        // We explicitly do NOT include the 'participantName' or 'country' in the response.
        ParticipantResponseDto cleanResponse = new ParticipantResponseDto(
                newParticipant.getParticipantId(), // Safe: Generated by DB
                newParticipant.getParticipantCode(), // Safe: We know this passed sanitizeStrict()
                "CREATED",                         // Safe: Hardcoded
                "Participant registered successfully." // Safe: Hardcoded
        );

        // 4. SECURITY HEADERS
        HttpHeaders headers = new HttpHeaders();
        headers.add("X-Content-Type-Options", "nosniff");
        headers.setContentType(MediaType.APPLICATION_JSON);

        return new ResponseEntity<>(cleanResponse, headers, HttpStatus.CREATED);
    }

    /**
     * Strict Whitelist Sanitizer.
     * Only allows A-Z, 0-9, hyphens, and underscores.
     */
    private String sanitizeStrict(String input) {
        if (input == null) return null;
        return input.replaceAll("[^a-zA-Z0-9-_]", "");
    }
}