package com.chiyumechunga.backend.dto;

import com.chiyumechunga.backend.model.ParticipantType;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

public record ParticipantRegistrationDto(
        @NotBlank(message = "Participant Code is required")
        String participantCode, // e.g. "ZAMRA-001"

        @NotBlank(message = "Name is required")
        String participantName,

        @NotNull(message = "Type is required")
        ParticipantType participantType,

        @NotBlank(message = "Country is required")
        String country,

        // Ideally, this is the public key generated by their Firefly Node
        @NotBlank(message = "Blockchain Enrollment ID (Wallet Address) is required")
        String blockchainEnrollmentId
) {}