spring.application.name=backend
# Server Port for your Spring Backend
server.port=8080

# Database Configuration (PostgreSQL - Off-chain DB)
spring.datasource.url=jdbc:postgresql://localhost:5432/pharma_integrity_sys
spring.datasource.username=pharma_user
spring.datasource.password=qwertyuiop
spring.jpa.hibernate.ddl-auto=update

# Firefly Configuration (Connecting to Node 0 of your 'pis' stack)
firefly.api.url=http://localhost:7000/api/v1
firefly.namespace=default